# Generated by Django 2.2.5 on 2020-06-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum',
            new_name='Board',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='forum',
            new_name='board',
        ),
    ]
