# Generated by Django 2.2.5 on 2020-05-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=264)),
                ('starting', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=264, null=True)),
                ('name', models.CharField(blank=True, max_length=264)),
                ('link', models.CharField(blank=True, max_length=264)),
                ('platform', models.CharField(blank=True, max_length=264)),
                ('ending', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
