# Generated by Django 2.2.5 on 2020-04-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('writers', models.CharField(max_length=300)),
                ('starting', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=20)),
            ],
        ),
    ]
