# Generated by Django 2.2.5 on 2020-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='starting',
            field=models.DateTimeField(),
        ),
    ]
