# Generated by Django 2.2.5 on 2020-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20200430_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='starting',
            field=models.DateTimeField(null=True),
        ),
    ]
