# Generated by Django 2.2.5 on 2020-05-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20200430_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CC_Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestCode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Contest',
            new_name='CF_Contest',
        ),
    ]
