# Generated by Django 2.2.5 on 2020-05-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20200502_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='cc_contest',
            name='contest_link',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
