# Generated by Django 2.2.5 on 2020-05-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_cc_contest_contest_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('starting', models.DateTimeField(null=True)),
                ('length', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='CC_Contest',
        ),
        migrations.DeleteModel(
            name='CF_Contest',
        ),
    ]
