# Generated by Django 2.2.5 on 2020-05-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20200508_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='ContestSite',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='contestId',
            field=models.CharField(max_length=200),
        ),
    ]
