# Generated by Django 2.2.5 on 2020-05-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20200509_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='platform',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
