# Generated by Django 2.2.5 on 2020-05-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_contests_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='ending',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
